networks:
  mailing-network:
    driver: bridge

services:
  rabbitmq:
    container_name: mailing-ms-rabbitmq
    image: "rabbitmq:3.8.3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - mailing-network
  redis:
    container_name: mailing-ms-redis
    image: 'redis:alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=${REDIS_PORT}
    ports:
      - '6379:6379'
    networks:
      - mailing-network
  mongo:
    container_name: mailing-ms-mongo
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - '27017:27017'
    networks:
      - mailing-network