networks:
  notifications-network:
    driver: bridge

services:
  redis:
    image: 'redis:alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=${REDIS_PORT}
    ports:
      - '6379:6379'
    networks:
      - notifications-network
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - notifications-network